services:
  # Laravel Application Service
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bizportalv1
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - bizportalv1-network

  # Frontend Development Service (React + Vite)
  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - bizportalv1-network
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

  # MySQL Database Service
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bizportalv1
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: bizportalv1
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - bizportalv1-network

  # phpMyAdmin for Database Management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret
    depends_on:
      - db
    networks:
      - bizportalv1-network

volumes:
  mysql_data:

networks:
  bizportalv1-network:
    driver: bridge 